### ISSUE TITLE
Movement Rate Not Editable, Also not converted correctly from previous version.

### ISSUE THREAD

**Issue by lonpalmer** [vttred/Old-School-Essentials-Advanced-Fantasy-for-Foundry-VTT#10]
### What happened?

The base movement rate on the character sheets are not editable.  Further, characters who were created in previous version of the system have wrong numbers in their base movement rate. 

<img width="930" alt="Screenshot 2023-05-27 at 9 23 42 AM" src="https://github.com/vttred/Old-School-Essentials-Advanced-Fantasy-for-Foundry-VTT/assets/13160715/ca5140f3-84ba-4338-ba09-02ecf3ef50a2">

### What is the expected behaviour?

The movement base movement rate should be editable for all characters.

### Relevant Errors and Warnings

```shell
N/A
```

### Additional Support Details

Foundry Virtual Tabletop: Version 11 Stable, 11.299
Game System: ose, 1.9.1
Active Modules: 30
Performance Mode: 3

OS: Unknown
Client: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.57
GPU: ANGLE (Apple, Apple M1, OpenGL 4.1)
Max Texture Size: 16384

Scene: 5412 x 3678 | Grid Size: 108 | Padding Percentage: 0.25
Walls: 38 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 1

Actors: 392 | Items: 723 | Journal Entries: 66 | Rollable Tables: 31 |
Playlists: 1 | Compendium Packs: 54 | Chat Messages: 4

### Foundry VTT Core Version

V11

### Old-School Essentials Core Version

1.9.1

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
Sorry that I've just only answered this today!

The movement rate bug was reported in https://github.com/vttred/ose/issues/446, has now been resolved in https://github.com/vttred/ose/pull/450, and is awaiting release in `ose` 1.9.2, expected today

Thanks for reporting! I'll be closing this issue

**Comment by PXR5** [comment]
15/10/23
I am seeing this same problem in Foundry 11.313, OSE 1.9.3. The incorrect values are not editable.

<img width="804" alt="Screenshot 2023-10-15 at 16 51 14" src="https://github.com/vttred/Old-School-Essentials-Advanced-Fantasy-for-Foundry-VTT/assets/21021737/35af5445-8afe-4c03-8c52-f4997616efb1">
