### ISSUE TITLE
Links to Treasure Type table is broken for Monsters.

### ISSUE THREAD

**Issue by lonpalmer** [vttred/Old-School-Essentials-Advanced-Fantasy-for-Foundry-VTT#7]
### What happened?

Links for Treasure Type Table is broken in monster stat  blocks from the compendium.  The treasure tables are present in their proper compendium and can be added to the monster block manually.

<img width="984" alt="image" src="https://github.com/vttred/Old-School-Essentials-Advanced-Fantasy-for-Foundry-VTT/assets/13160715/7ad391c5-719d-460e-880c-354b42895c79">

### What is the expected behaviour?

Link should not be broken 

### Relevant Errors and Warnings

```shell
No errors in  console
```

### Additional Support Details

Foundry Virtual Tabletop: Version 11 Stable, 11.299
Game System: ose, 1.9.1
Active Modules: 27
Performance Mode: 3

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.50
GPU: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 1210 x 1186 | Grid Size: 100 | Padding Percentage: 0
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 0

Actors: 24 | Items: 0 | Journal Entries: 33 | Rollable Tables: 3 |
Playlists: 1 | Compendium Packs: 30 | Chat Messages: 4

### Foundry VTT Core Version

V11

### Old-School Essentials Core Version

1.9.1

### Please update your browser regularly. Which (updated) browsers are you seeing the problem on?

Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonyronda** [comment]
Thanks for another report! Another user pointed this out (and I've been a bit busy to log it yet), and they discovered that you should be able to temporarily alleviate this by importing all of your treasure tables to your world. This is the main reason I hadn't discovered any broken links

**Comment by anthonyronda** [comment]
As an update, this is now fixed and expected in release 1.0.3, coming out in a few hours

**Comment by anthonyronda** [comment]
Oops, I meant 1.0.2. Anyway the new version is released
